# Generated by Django 5.1.7 on 2025-09-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('current_step', models.CharField(max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('triggered_by_event_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wake_at', models.DateTimeField(blank=True, null=True)),
                ('waiting_signal', models.CharField(blank=True, max_length=100)),
                ('on_timeout_step', models.CharField(blank=True, max_length=100)),
                ('error', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'waiting_signal'], name='workflows_w_status_a51e27_idx'), models.Index(fields=['status', 'wake_at'], name='workflows_w_status_e0f85b_idx'), models.Index(fields=['triggered_by_event_id'], name='workflows_w_trigger_eb508c_idx')],
            },
        ),
    ]
