# Generated by Django 5.1.7 on 2025-10-07 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_workflowrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='StepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='workflows.workflowrun')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['workflow_run', 'created_at'], name='workflows_s_workflo_14bae3_idx')],
            },
        ),
    ]
