# Generated by Django 5.1.7 on 2025-10-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflowrun_progress_stepexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='completion_display',
            field=models.JSONField(blank=True, default=dict, help_text='Display metadata for completion state: {display_title, display_subtitle}'),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='waiting_display',
            field=models.JSONField(blank=True, default=dict, help_text='Display metadata for waiting state: {display_title, display_subtitle, display_waiting_for}'),
        ),
    ]
