# Generated by Django 5.1.7 on 2025-10-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_workflowrun_completion_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='active_subworkflow_run_id',
            field=models.IntegerField(blank=True, help_text='Currently active child subworkflow', null=True),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='parent_run_id',
            field=models.IntegerField(blank=True, help_text='Parent workflow if this is a subworkflow', null=True),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['parent_run_id'], name='workflows_w_parent__a31fa4_idx'),
        ),
    ]
