# Generated by Django 5.1.7 on 2025-11-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_workflowrun_active_subworkflow_run_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepexecution',
            name='step_display',
            field=models.JSONField(blank=True, default=dict, help_text='Display metadata captured at execution time: {visible, step_title, step_type}'),
        ),
    ]
