# Generated by Django 5.1.7 on 2025-11-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_add_step_display_to_stepexecution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepexecution',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
