# Generated by Django 5.1.7 on 2025-10-11 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='files.folder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ManagedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ocr_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.folder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCROutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('parser_class', models.CharField(help_text="Full path to the parser class used (e.g., 'django_ai.files.parsers.TikaParser')", max_length=255)),
                ('parser_version', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Time taken to process in milliseconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('managed_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_outputs', to='files.managedfile')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', 'parent'], name='files_folde_owner_i_385c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['name'], name='files_folde_name_83b198_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'parent', 'owner')},
        ),
        migrations.AddIndex(
            model_name='managedfile',
            index=models.Index(fields=['owner', '-created_at'], name='files_manag_owner_i_6fe181_idx'),
        ),
        migrations.AddIndex(
            model_name='managedfile',
            index=models.Index(fields=['folder', '-created_at'], name='files_manag_folder__c0a0ea_idx'),
        ),
        migrations.AddIndex(
            model_name='managedfile',
            index=models.Index(fields=['ocr_status'], name='files_manag_ocr_sta_5cd76e_idx'),
        ),
        migrations.AddIndex(
            model_name='managedfile',
            index=models.Index(fields=['mime_type'], name='files_manag_mime_ty_0d4ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='ocroutput',
            index=models.Index(fields=['managed_file', '-processed_at'], name='files_ocrou_managed_7ab224_idx'),
        ),
        migrations.AddIndex(
            model_name='ocroutput',
            index=models.Index(fields=['parser_class'], name='files_ocrou_parser__21e293_idx'),
        ),
        migrations.AddIndex(
            model_name='ocroutput',
            index=models.Index(fields=['success'], name='files_ocrou_success_3e90d6_idx'),
        ),
    ]
