# Generated by Django 5.1.7 on 2025-10-11 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_managedfile_ocr_status_alter_ocroutput_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
    ]
