# Generated by Django 5.1.7 on 2025-10-13 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_folder_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files.folder'),
        ),
    ]
