# Generated by Django 5.1.7 on 2025-10-13 14:11

import django_ai.tables.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='file',
            field=models.FileField(upload_to=django_ai.tables.models.table_upload_path),
        ),
    ]
