# Generated by Django 5.1.7 on 2025-09-06 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_id', models.CharField(blank=True, help_text='For anonymous users', max_length=255)),
                ('context', models.JSONField(default=dict, help_text='Session context data')),
                ('metadata', models.JSONField(default=dict, help_text='UI and custom metadata')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to='conversation_files/%Y/%m/%d/')),
                ('filename', models.TextField(blank=True, help_text='Original filename')),
                ('content_type', models.CharField(blank=True, help_text='MIME type', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True, help_text='Cached extracted text', null=True)),
                ('text_extracted_at', models.DateTimeField(blank=True, help_text='When text was last extracted', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional file metadata', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='conversations.conversationsession')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('agent', 'Agent Response'), ('system', 'System Message'), ('widget', 'Widget Display')], max_length=20)),
                ('content', models.TextField()),
                ('component_type', models.CharField(blank=True, max_length=100)),
                ('component_data', models.JSONField(default=dict)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', help_text='Processing status for user messages', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversationsession')),
                ('files', models.ManyToManyField(blank=True, related_name='messages', to='conversations.file')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
