# Generated by Django 5.1.7 on 2025-09-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='agent_path',
            field=models.CharField(default='', help_text="Agent name from registry like 'support', 'sales', etc.", max_length=255),
            preserve_default=False,
        ),
    ]
