# Generated by Django 5.1.7 on 2025-10-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='files',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
