# Generated by Django 5.1.7 on 2025-10-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_remove_conversationmessage_files_delete_file'),
        ('files', '0002_alter_managedfile_ocr_status_alter_ocroutput_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='conversation_messages', to='files.managedfile'),
        ),
    ]
