# Generated by Django 5.1.7 on 2025-10-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_conversationmessage_files'),
        ('tables', '0002_alter_table_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='tables',
            field=models.ManyToManyField(blank=True, related_name='conversation_messages', to='tables.table'),
        ),
    ]
