# Generated by Django 5.1.7 on 2025-10-14 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversationmessage_tables'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionToolLoadout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadout', models.ForeignKey(help_text='The tool loadout configuration', on_delete=django.db.models.deletion.CASCADE, to='tools.toolloadout')),
                ('session', models.OneToOneField(help_text='The conversation session', on_delete=django.db.models.deletion.CASCADE, related_name='tool_loadout', to='conversations.conversationsession')),
            ],
            options={
                'verbose_name': 'Session Tool Loadout',
                'verbose_name_plural': 'Session Tool Loadouts',
            },
        ),
    ]
