# Generated by Django 5.1.7 on 2025-10-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_sessiontoolloadout'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationwidget',
            name='display_data',
            field=models.JSONField(default=dict, help_text='UI state: position, size, minimized, closed'),
        ),
    ]
