# Generated by Django 5.1.7 on 2025-10-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_conversationwidget_display_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationwidget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
