# Generated by Django 5.1.7 on 2025-08-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ITImmediate',
        ),
        migrations.DeleteModel(
            name='ITScheduled',
        ),
    ]
