# Generated by Django 5.1.7 on 2025-10-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolLoadout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_tools', models.JSONField(default=list, help_text='List of additional tool names beyond base tools')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tool Loadout',
                'verbose_name_plural': 'Tool Loadouts',
            },
        ),
    ]
