# Generated by Django 5.1.7 on 2025-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='triggered_by_event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['triggered_by_event_id'], name='workflows_w_trigger_eb508c_idx'),
        ),
    ]
