# Generated by Django 5.1.7 on 2025-12-11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration for handler-based agents.

    This is a BREAKING CHANGE that removes the legacy act()-based agent system
    and replaces it with the new handler-based agent system.

    WARNING: This migration will DROP all existing AgentRun and AgentExecutionLog
    data. Only run this if no production agents exist.
    """

    dependencies = [
        ('agents', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        # Drop old models
        migrations.DeleteModel(
            name='AgentExecutionLog',
        ),
        migrations.DeleteModel(
            name='AgentRun',
        ),

        # Create new AgentRun model
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=255)),
                ('namespace', models.CharField(max_length=255)),
                ('entity_id', models.CharField(blank=True, max_length=50)),
                ('context', models.JSONField(default=dict)),
                ('status', models.CharField(
                    choices=[
                        ('active', 'Active'),
                        ('completed', 'Completed'),
                        ('failed', 'Failed'),
                    ],
                    default='active',
                    max_length=20,
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='contenttypes.contenttype',
                )),
            ],
            options={
                'indexes': [
                    models.Index(fields=['agent_name', 'status'], name='agents_agen_agent_n_new_idx'),
                    models.Index(fields=['namespace'], name='agents_agen_namespa_idx'),
                    models.Index(fields=['agent_name', 'namespace', 'status'], name='agents_agen_agent_ns_idx'),
                ],
            },
        ),

        # Create new HandlerExecution model
        migrations.CreateModel(
            name='HandlerExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler_name', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('offset_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('running', 'Running'),
                        ('completed', 'Completed'),
                        ('failed', 'Failed'),
                        ('skipped', 'Skipped'),
                    ],
                    default='pending',
                    max_length=20,
                )),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('agent_run', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='executions',
                    to='agents.agentrun',
                )),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'indexes': [
                    models.Index(fields=['agent_run', 'status'], name='agents_hand_agent_r_idx'),
                    models.Index(fields=['status', 'scheduled_at'], name='agents_hand_status_idx'),
                    models.Index(fields=['handler_name', 'status'], name='agents_hand_handler_idx'),
                ],
            },
        ),
    ]
