# Generated by Django 5.1.7 on 2025-12-11 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_handler_based_agents'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentrun',
            new_name='agents_agen_agent_n_5c7623_idx',
            old_name='agents_agen_agent_n_new_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrun',
            new_name='agents_agen_namespa_191b0f_idx',
            old_name='agents_agen_namespa_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrun',
            new_name='agents_agen_agent_n_8c392a_idx',
            old_name='agents_agen_agent_ns_idx',
        ),
        migrations.RenameIndex(
            model_name='handlerexecution',
            new_name='agents_hand_agent_r_446f53_idx',
            old_name='agents_hand_agent_r_idx',
        ),
        migrations.RenameIndex(
            model_name='handlerexecution',
            new_name='agents_hand_status_ff94a6_idx',
            old_name='agents_hand_status_idx',
        ),
        migrations.RenameIndex(
            model_name='handlerexecution',
            new_name='agents_hand_handler_0b4184_idx',
            old_name='agents_hand_handler_idx',
        ),
    ]
