# Generated by Django 5.1.7 on 2025-12-12 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_rename_agents_agen_agent_n_new_idx_agents_agen_agent_n_5c7623_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handlerexecution',
            name='offset_minutes',
        ),
        migrations.AddField(
            model_name='handlerexecution',
            name='offset',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
