# Generated by Django 5.1.7 on 2025-08-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_at',
            new_name='event_created_at',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='updated_at',
            new_name='event_updated_at',
        ),
    ]
