# Generated by Django 5.1.7 on 2025-08-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_testbooking_testmodelwithoutevents_testorder_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestBooking',
        ),
        migrations.DeleteModel(
            name='TestModelWithoutEvents',
        ),
        migrations.DeleteModel(
            name='TestOrder',
        ),
        migrations.DeleteModel(
            name='TestProperty',
        ),
    ]
