# Generated by Django 5.1.7 on 2025-09-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_testbooking_delete_testmodelwithoutevents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='namespace',
            field=models.CharField(default='*', help_text='Namespace to scope events and prevent cross-application triggering', max_length=255),
        ),
    ]
