# Generated by Django 5.1.7 on 2025-09-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0005_event_namespace'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('model_type', 'entity_id', 'event_name', 'namespace')},
        ),
    ]
