# Generated by Django 5.1.7 on 2025-12-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_args', models.JSONField(default=list)),
                ('task_kwargs', models.JSONField(default=dict)),
                ('debounce_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('collected_args', models.JSONField(default=list)),
                ('run_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'run_at'], name='timers_time_status_f7bb00_idx')],
            },
        ),
    ]
