# Generated by Django 5.1.7 on 2025-12-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedtask',
            name='debounce_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
