# Generated by Django 5.1.7 on 2025-12-28 01:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0002_alter_timedtask_debounce_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timedtask',
            options={'ordering': ['-dispatched_at']},
        ),
        migrations.RemoveIndex(
            model_name='timedtask',
            name='timers_time_status_f7bb00_idx',
        ),
        migrations.RemoveField(
            model_name='timedtask',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='timedtask',
            name='status',
        ),
        migrations.RemoveField(
            model_name='timedtask',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='timedtask',
            name='error_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timedtask',
            name='success',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='timedtask',
            name='debounce_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timedtask',
            name='dispatched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timedtask',
            name='run_at',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='timedtask',
            index=models.Index(fields=['debounce_key'], name='timers_time_debounc_2f1c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='timedtask',
            index=models.Index(fields=['dispatched_at'], name='timers_time_dispatc_779ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='timedtask',
            index=models.Index(fields=['task_name'], name='timers_time_task_na_b934d5_idx'),
        ),
    ]
