# Generated by Django 5.1.7 on 2025-09-03 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_version', models.CharField(default='1', max_length=20)),
                ('context_data', models.JSONField(default=dict)),
                ('namespaces', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('running', 'Running'), ('waiting', 'Waiting'), ('finished', 'Finished'), ('failed', 'Failed')], default='running', max_length=20)),
                ('triggering_event_id', models.IntegerField(blank=True, null=True)),
                ('current_event_id', models.IntegerField(blank=True, null=True)),
                ('current_event_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wake_at', models.DateTimeField(blank=True, null=True)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['agent_name', 'status'], name='agents_agen_agent_n_5c7623_idx'), models.Index(fields=['status', 'wake_at'], name='agents_agen_status_df2867_idx'), models.Index(fields=['triggering_event_id'], name='agents_agen_trigger_01364d_idx'), models.Index(fields=['agent_name'], name='agent_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('event_name', models.CharField(blank=True, max_length=100)),
                ('execution_type', models.CharField(max_length=20)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('context_before', models.JSONField(blank=True, null=True)),
                ('context_after', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='agents.agentrun')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['agent_run', '-started_at'], name='agents_agen_agent_r_a660b5_idx'), models.Index(fields=['success', 'execution_type'], name='agents_agen_success_b08958_idx')],
            },
        ),
    ]
