# Generated by Django 5.1.7 on 2025-11-30 21:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_guest_testbooking_testmodelwithoutevents_testorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUUIDModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
