# Generated by Django 5.1.7 on 2025-12-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_testuuidmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTriggerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
    ]
