# Generated by Django 5.1.7 on 2025-12-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_add_testtriggermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestWatchFieldsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
