# Generated by Django 5.1.7 on 2025-12-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_add_watch_fields_test_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTemplatedEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
