# Generated by Django 5.1.7 on 2025-12-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebouncedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debounce_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('task_name', models.CharField(max_length=255)),
                ('task_args_json', models.TextField(default='[]')),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['scheduled_at'], name='queues_debo_schedul_605957_idx')],
            },
        ),
    ]
