# Generated by Django 5.1.7 on 2025-12-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debouncedtask',
            name='event_ids_json',
            field=models.TextField(default='[]'),
        ),
    ]
