# Generated by Django 5.1.7 on 2025-09-04 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('entity_id', models.CharField(max_length=50)),
                ('event_created_at', models.DateTimeField(auto_now_add=True)),
                ('event_updated_at', models.DateTimeField(auto_now=True)),
                ('namespace', models.CharField(default='*', help_text='Namespace to scope events and prevent cross-application triggering', max_length=255)),
                ('model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='events_even_status_5709b6_idx'), models.Index(fields=['model_type', 'entity_id'], name='events_even_model_t_cf9d32_idx')],
                'unique_together': {('model_type', 'entity_id', 'event_name', 'namespace')},
            },
        ),
    ]
