# Generated by Django 5.1.7 on 2025-12-12 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEventOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.DurationField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_offsets', to='events.event')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'offset'], name='events_proc_event_i_6b72db_idx')],
                'unique_together': {('event', 'offset')},
            },
        ),
    ]
