# Generated by Django 5.1.7 on 2025-12-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_processedeventoffset'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('match', models.JSONField()),
                ('owner_type', models.CharField(max_length=50)),
                ('owner_class', models.CharField(max_length=255)),
                ('owner_run_id', models.BigIntegerField()),
                ('priority', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_events', models.IntegerField(blank=True, null=True)),
                ('events_handled', models.IntegerField(default=0)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'expires_at'], name='events_even_event_t_e4626b_idx'), models.Index(fields=['owner_type', 'owner_run_id'], name='events_even_owner_t_f14786_idx')],
            },
        ),
    ]
