# Generated by Django 5.1.7 on 2025-12-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='watched_values',
            field=models.JSONField(blank=True, help_text='Snapshot of watched field values for change detection', null=True),
        ),
    ]
