# Generated by Django 5.1.7 on 2025-12-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_add_watched_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='watched_values',
        ),
        migrations.AddField(
            model_name='event',
            name='watched_values_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of watched field values for change detection', max_length=64, null=True),
        ),
    ]
